# https://dart.dev/guides/language/analysis-options
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Ideally we'd fix all of these - or ignore them at the line-level where
    # necessary
    camel_case_types: ignore
    non_constant_identifier_names: ignore

linter:
  rules:
  - avoid_bool_literals_in_conditional_expressions
  - avoid_private_typedef_functions
  - avoid_redundant_argument_values
  - avoid_returning_null
  - avoid_returning_null_for_future
  - avoid_returning_this
  - avoid_unused_constructor_parameters
  - cancel_subscriptions
  - join_return_with_assignment
  - literal_only_boolean_expressions
  - no_adjacent_strings_in_list
  - no_runtimeType_toString
  - package_api_docs
  - prefer_const_declarations
  - prefer_expression_function_bodies
  - prefer_final_locals
  - unnecessary_await_in_return
  - use_string_buffers
