# https://dart.dev/guides/language/analysis-options
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - test_fixes/**

  errors:
    # 43 instances in generated code.
    camel_case_types: ignore
    # 420 instances in the MDN docs.
    comment_references: ignore
    # 14 instances in the MDN docs.
    lines_longer_than_80_chars: ignore
    # 1,333 instances in generated code.
    non_constant_identifier_names: ignore
    # Consider removing from dart_flutter_team_lints.
    unreachable_from_main: ignore

linter:
  rules:
    avoid_bool_literals_in_conditional_expressions: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    join_return_with_assignment: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_runtimeType_toString: true
    package_api_docs: true
    prefer_const_declarations: true
    prefer_final_locals: true
    # MDN comments include HTML docs that trigger this lint. Reenable once
    # that's resolved.
    unintended_html_in_doc_comment: false
    unnecessary_await_in_return: true
    use_string_buffers: true
