export declare const myCustomEvent: CustomEvent;
export declare var myShadowRoot: ShadowRoot;
declare let myURL: URL;
export declare function handleMouseEvent(event: MouseEvent): void;
export declare function generateUrl(path: string): URL;
export declare function convertToWebGL(buffer: ArrayBuffer): Promise<WebGLBuffer>;
export declare function getHTMLElementContent<T extends HTMLElement>(element: T): string;
export declare const button: HTMLButtonElement;
declare const input: HTMLInputElement;
export declare const output: HTMLDivElement;
export declare function handleButtonClick(event: MouseEvent): void;
export declare function handleInputChange(event: Event): void;
