interface OrderedMap {
  readonly attribute unsigned long size;

  getter any (unsigned long index);
  setter undefined (unsigned long index, any value);

  getter any get(DOMString name);
  setter undefined set(DOMString name, any value);
};
