sdk:
- dev

stages:
- analyze_and_format:
  - analyze: --fatal-infos .
  - format:
- unit_test:
  - test: --test-randomize-ordering-seed=random -p chrome
  - test: --test-randomize-ordering-seed=random -p chrome -c dart2wasm
- generate_and_analyze:
  - command: dart bin/update_bindings.dart
  - analyze: --fatal-infos .
