name: package:js_interop_gen
permissions:
  contents: read

on:
  # Run CI on pushes to the main branch and on PRs.
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/js_interop_gen.yaml'
      - 'js_interop_gen/**'
  pull_request:
    paths:
      - '.github/workflows/js_interop_gen.yaml'
      - 'js_interop_gen/**'
  schedule:
    - cron: "0 0 * * 0"

defaults:
  run:
    working-directory: js_interop_gen/

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: ['3.12', dev]
        test_config: ['', '-p chrome', '-p chrome -c dart2wasm']

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 22
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1
        with:
          sdk: ${{ matrix.sdk }}

      - run: dart pub get
      - name: Install npm dependencies in js_interop_gen
        run: npm install
        working-directory: js_interop_gen/lib/src
      - name: Mark npm install as done
        run: touch .last_npm_install
        working-directory: js_interop_gen/lib/src
      - run: dart analyze --fatal-infos
        if: matrix.sdk == 'dev' && matrix.test_config == ''
      - run: dart analyze
        if: matrix.sdk != 'dev' && matrix.test_config == ''
      - run: dart test ${{ matrix.test_config }}
